baseURL = "https://strider-1977.hummel.casa/"
languageCode = "en-us"
title = "Strider 1977"

[taxonomies]
  tag = "tags"

[params]
    Title = ""
    site_description = ""
    # github_repo = "https://github.com/tphummel/strider-1977"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1