baseURL = "https://my.site/"
languageCode = "en-us"
title = "My Site"

[taxonomies]
  tag = "tags"

[params]
    Title = ""
    site_description = ""
    # github_repo = "https://github.com//"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1