name: Static Website Build and Deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v0.116.1/hugo_0.116.1_Linux-64bit.tar.gz
        tar xzvf hugo_0.116.1_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/
        sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
        sudo chmod o+x /usr/local/bin/jq
    - name: Build Website
      run: hugo
      env:
        HUGO_ENV: production
